version: '2'
services:
  wordpress:
    image: visiblevc/wordpress:latest
    ports:
      - 8080:80
      - 4040:443
    volumes:
      - ./certs:/certs
      - ./data:/data
      - ./wp-content/uploads:/app/wp-content/uploads
      - ./wp-content/themes/Luxcentric:/app/wp-content/themes/Luxcentric
      - ./wp-content/plugins/duplicate-tec-event:/app/wp-content/plugins/duplicate-tec-event
      - ./wp-content/plugins/events-calendar-pro:/app/wp-content/plugins/events-calendar-pro
      - ./wp-content/plugins/event-tickets:/app/wp-content/plugins/event-tickets
      - ./wp-content/plugins/event-tickets-plus:/app/wp-content/plugins/event-tickets-plus
      - ./wp-content/plugins/favicon-by-realfavicongenerator:/app/wp-content/plugins/favicon-by-realfavicongenerator
      - ./wp-content/plugins/gravityforms:/app/wp-content/plugins/gravityforms
      - ./wp-content/plugins/popup-maker:/app/wp-content/plugins/popup-maker
      - ./wp-content/plugins/reveal-ids-for-wp-admin-25:/app/wp-content/plugins/reveal-ids-for-wp-admin-25
      - ./wp-content/plugins/scalable-vector-graphics-svg:/app/wp-content/plugins/scalable-vector-graphics-svg
      - ./wp-content/plugins/testimonials-widget-premium:/app/wp-content/plugins/testimonials-widget-premium
      - ./wp-content/plugins/the-events-calendar:/app/wp-content/plugins/the-events-calendar
      - ./wp-content/plugins/woocommerce:/app/wp-content/plugins/woocommerce
      - ./wp-content/plugins/woothemes-sensei:/app/wp-content/plugins/woothemes-sensei
      - ./wp-content/plugins/woothemes-updater:/app/wp-content/plugins/woothemes-updater
    environment:
      DB_NAME: wordpress
      DB_PASS: root
      PLUGINS: >-
          [local]duplicate-tec-event,
          [local]events-calendar-pro,
          [local]event-tickets,
          [local]event-tickets-plus,
          [local]favicon-by-realfavicongenerator,
          [local]gravityforms,
          [local]popup-maker,
          [local]reveal-ids-for-wp-admin-25,
          [local]scalable-vector-graphics-svg,
          [local]testimonials-widget-premium,
          [local]the-events-calendar,
          [local]woocommerce,
          [local]woothemes-sensei,
          [local]woothemes-updater
      THEMES: >-
          [local]Luxcentric
      SEARCH_REPLACE: luxcentric.com,localhost:4040
  phpmyadmin:   
    image: phpmyadmin/phpmyadmin
    environment:
      MYSQL_ROOT_PASSWORD: root
    ports:
      - 22222:80
  db:
    image: mariadb:10 # or mysql:5.7
    volumes:
      - data:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: root
volumes:
  data: {}
