version: '3'
services:
  wordpress:
    image: visiblevc/wordpress:0.15.2-php7.0
    ports:
      - 8080:80
      - 4040:443
    volumes:
      - ./certs:/certs
      - ./data:/data
      - ./wp-content/uploads:/app/wp-content/uploads
      - ./wp-content/themes/Luxcentric:/app/wp-content/themes/Luxcentric
      - ./wp-content/plugins:/app/wp-content/plugins
    environment:
      DB_NAME: wordpress
      DB_PASS: root
      URL_REPLACE: luxcentric.com,localhost:4040
      WP_DEBUG: 'true'
      WP_DEBUG_LOG: 'true'
      WP_DEBUG_DISPLAY: 'true'
  phpmyadmin:   
    image: phpmyadmin/phpmyadmin
    environment:
      MYSQL_ROOT_PASSWORD: root
    ports:
      - 22222:80
  db:
    image: mariadb:10 # or mysql:5.7
    volumes:
      - data:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: root
volumes:
  data: {}
